name = "amazone" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "ilped.isppaintechidn.cloud.amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "gw.ruangguru.com.amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "creativeservices.netflix.com.amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "poe.garena.com.amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "www.sushiroll.co.id.amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "support.udemy.com.amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "cdn-cf.zoom.us.amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "df.game.naver.com.amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "nontontv.vidio.com.amazone.vip-server.cloud"
custom_domain = true
[[routes]]
pattern = "app.midtrans.com.amazone.vip-server.cloud"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "e0b094e3-ec8a-46c5-a6c6-98cd478c33d5"
